AllCops:
  NewCops: disable
  DisabledByDefault: true
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'etc/**/*'
    - 'guides/**/*'
    - 'lib/**/*'
    - 'vendor/**/*'

Style:
  Enabled: true

Layout:
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Style/GuardClause:
  Enabled: false