name: Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: mysecretpassword
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run Rubocop
        run: bundle exec rubocop

      - name: Run Minitest
        run: |
          bundle exec rake db:setup
          bundle exec rake test
        env:
          RAILS_ENV: test
          POSTGRES_USER: root
          POSTGRES_PASSWORD: mysecretpassword
